import {StyleSheet, Dimensions} from 'react-native';

const styles = StyleSheet.create({
  largeScreen: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'flex-end',
    marginBottom: 40,
    backgroundColor: '#E0E0E0',
  },
  smallScreen: {},
  image: {
    width: '100%',
    height: 615,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
  title: {
    fontSize: 100,
    fontWeight: 'bold',
    color: 'white',
    width: '70%',
    marginLeft: 25,
  },
  button: {
    backgroundColor: '#fff',
    width: 200,
    height: 40,
    borderRadius: 10,
    marginTop: 15,
    marginLeft: 25,
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 3,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  largeScreenSearchButton: {
    backgroundColor: '#fff',
    height: 55,
    width: Dimensions.get('screen').width - 40,
    borderRadius: 28,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 40,
    zIndex: 3,
  },
  smallScreenSearchButton: {
    backgroundColor: '#fff',
    height: 55,
    width: Dimensions.get('screen').width - 40,
    borderRadius: 28,
    marginHorizontal: 20,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
    top: 20,
    zIndex: 3,
  },
  searchButtonText: {
    fontSize: 16,
    fontWeight: 'bold',
  },
  container: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 2,
  },
});

export default styles;
